# Generated by Django 5.1.6 on 2025-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
